version: '3'

services:
    anaconda:
        container_name: 'anaconda'
        build: .
        ports: 
            - '8889:8888'
        tty: true
        volumes:
            - '/c/kussy-lab/python:/work'
